-- SPLove+ incremental features (minimal, additive)

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS is_active_mode BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.user_engagement (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  response_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
  proposal_accept_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
  reliability_score NUMERIC(5,2) NOT NULL DEFAULT 0,
  reliability_label TEXT NOT NULL DEFAULT 'Medium',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT user_engagement_reliability_label_check
    CHECK (reliability_label IN ('High', 'Medium', 'Low'))
);

CREATE TABLE IF NOT EXISTS public.user_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT user_availability_range_check CHECK (end_time > start_time)
);

CREATE INDEX IF NOT EXISTS idx_user_availability_user_day
  ON public.user_availability(user_id, day_of_week, start_time);

CREATE OR REPLACE FUNCTION public.touch_user_engagement_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_user_engagement_updated_at ON public.user_engagement;
CREATE TRIGGER trg_user_engagement_updated_at
BEFORE UPDATE ON public.user_engagement
FOR EACH ROW
EXECUTE FUNCTION public.touch_user_engagement_updated_at();

CREATE OR REPLACE FUNCTION public.touch_user_availability_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_user_availability_updated_at ON public.user_availability;
CREATE TRIGGER trg_user_availability_updated_at
BEFORE UPDATE ON public.user_availability
FOR EACH ROW
EXECUTE FUNCTION public.touch_user_availability_updated_at();

ALTER TABLE public.user_engagement ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_availability ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_engagement_select_authenticated" ON public.user_engagement;
CREATE POLICY "user_engagement_select_authenticated"
  ON public.user_engagement
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "user_engagement_upsert_own" ON public.user_engagement;
CREATE POLICY "user_engagement_upsert_own"
  ON public.user_engagement
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "user_availability_select_authenticated" ON public.user_availability;
CREATE POLICY "user_availability_select_authenticated"
  ON public.user_availability
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "user_availability_write_own" ON public.user_availability;
CREATE POLICY "user_availability_write_own"
  ON public.user_availability
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
